language: python
python:
  - "3.7"
  - "3.8-dev"

dist: xenial
sudo: true

stages:
  - tests

install:
  - pip install --upgrade pip
  - pip install poetry
  - poetry install

jobs:
  include:
    - stage: test
      name: lint
      script:
        - poetry run flake8
        - poetry run black --check .
    - stage: test
      name: tests
      script:
        - tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)