language: python
python: 3.7
dist: xenial
sudo: true

stages:
  - tests

install:
  - pip install poetry
  - poetry install

jobs:
  include:
    - stage: test
      name: lint
      script:
        - poetry run flake8
        - poetry run black --check .
    - stage: test
      name: tests
      script: poetry run tox